name = "beauty-salon"
main = "_worker.js"
compatibility_date = "2026-08-06"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "beauty_db"
database_id = "beauty_db"
